name: Publish

on:
  release:
    types: [published, edited]

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: 
          - 'amd64'
          - 'arm64'
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
          - 'macos-latest'
        go:
          - '1.21'
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-go@v4'
        with:
          go-version: '${{ matrix.go }}'
      - name: "go test"
        run: |
          go test -count=1 -race -timeout=10m ./...
      - name: 'go build'
        env:
          CGO_ENABLED: 0
        run: |
          go build -ldflags="-s -w" -o $ARTIFACT_NAME ./cmd/${{ matrix.action }}/...
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
