name: Publish

on:
  release:
    types: [published, edited]

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  call-test-and-build:
    uses: ./.github/workflows/common.yaml
  assemble-and-tag:
    runs-on: 'ubuntu-latest'
    needs: [ call-test-and-build ]
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3

      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: bin/

      - run: ls -R
      - run: chmod +x bin/*
      - name: Assemble and Tag
        uses: ./
        env:
          GITHUB_TOKEN: ${{ github.token }}
